int printf();
int strlen();
int memcmp();
int exit();
void *calloc();
int isspace();
int isdigit();
int strncmp();
int strtol();
int strncpy();
int free();
int snprintf();
char *strstr();
void *fopen();
int fseek();
int ftell();
int fread();
int fclose();
int sprintf();
int strcmp();
int fprintf();
int putchar();
char *strerror();
char *strcat();
char *strncat();

// int NULL = 0;
// typedef int size_t;
// typedef char bool;
// int false = 0;
// int true = 1;
// typedef void FILE;
// int stderr = 2;
// int errno = 0;
